<?php
declare(strict_types=1);

// ForeignExchangeRates SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

ForeignExchangeRatesUtility::setRegistrar(function (ForeignExchangeRatesUtility $u): void {
    $u->clean = [ForeignExchangeRatesClean::class, 'call'];
    $u->done = [ForeignExchangeRatesDone::class, 'call'];
    $u->make_error = [ForeignExchangeRatesMakeError::class, 'call'];
    $u->feature_add = [ForeignExchangeRatesFeatureAdd::class, 'call'];
    $u->feature_hook = [ForeignExchangeRatesFeatureHook::class, 'call'];
    $u->feature_init = [ForeignExchangeRatesFeatureInit::class, 'call'];
    $u->fetcher = [ForeignExchangeRatesFetcher::class, 'call'];
    $u->make_fetch_def = [ForeignExchangeRatesMakeFetchDef::class, 'call'];
    $u->make_context = [ForeignExchangeRatesMakeContext::class, 'call'];
    $u->make_options = [ForeignExchangeRatesMakeOptions::class, 'call'];
    $u->make_request = [ForeignExchangeRatesMakeRequest::class, 'call'];
    $u->make_response = [ForeignExchangeRatesMakeResponse::class, 'call'];
    $u->make_result = [ForeignExchangeRatesMakeResult::class, 'call'];
    $u->make_point = [ForeignExchangeRatesMakePoint::class, 'call'];
    $u->make_spec = [ForeignExchangeRatesMakeSpec::class, 'call'];
    $u->make_url = [ForeignExchangeRatesMakeUrl::class, 'call'];
    $u->param = [ForeignExchangeRatesParam::class, 'call'];
    $u->prepare_auth = [ForeignExchangeRatesPrepareAuth::class, 'call'];
    $u->prepare_body = [ForeignExchangeRatesPrepareBody::class, 'call'];
    $u->prepare_headers = [ForeignExchangeRatesPrepareHeaders::class, 'call'];
    $u->prepare_method = [ForeignExchangeRatesPrepareMethod::class, 'call'];
    $u->prepare_params = [ForeignExchangeRatesPrepareParams::class, 'call'];
    $u->prepare_path = [ForeignExchangeRatesPreparePath::class, 'call'];
    $u->prepare_query = [ForeignExchangeRatesPrepareQuery::class, 'call'];
    $u->graphql_body = [ForeignExchangeRatesGraphql::class, 'body'];
    $u->graphql_errors = [ForeignExchangeRatesGraphql::class, 'errors'];
    $u->result_basic = [ForeignExchangeRatesResultBasic::class, 'call'];
    $u->result_body = [ForeignExchangeRatesResultBody::class, 'call'];
    $u->result_headers = [ForeignExchangeRatesResultHeaders::class, 'call'];
    $u->transform_request = [ForeignExchangeRatesTransformRequest::class, 'call'];
    $u->transform_response = [ForeignExchangeRatesTransformResponse::class, 'call'];
});
